--Create the NOBEL_WIN table if it does not exist
CREATE TABLE IF NOT EXISTS NOBEL_WIN (
  YEAR INTEGER,
  SUBJECT TEXT,
  WINNER TEXT,
  COUNTRY TEXT,
  CATEGORY TEXT
);

--Insert sample data into the NOBEL_WIN table
INSERT INTO NOBEL_WIN (YEAR, SUBJECT, WINNER, COUNTRY, CATEGORY) VALUES
 (1970, 'PHYSICS', 'HANNES ALFVEN', 'SWEDEN', 'SCIENTIST'),
 (1970, 'PHYSICS', 'LOUIS NEEL', 'FRANCE', 'SCIENTIST'),
 (1971, 'PHYSICS', 'PAUL', 'FRANCE', 'SCIENTIST'),
 (1971, 'CHEMISTRY', 'HAMILTON', 'SWEDEN', 'LINGUIST'),
 (1972, 'LITERATURE', 'BERNARD KELSON', 'GERMANY', 'ECONOMIST'),
 (1972, 'ECONOMICS', 'JOSEPH', 'RUSSIA', 'ECONOMIST'),
 (1973, 'BIOLOGY', 'PHILIPS', 'USA', 'PRIME MINISTER'),
 (1980, 'BIOLOGY', 'MARTIN', 'USA', 'PRESIDENT'),
 (1981, 'PHYSIOLOGY', 'HANNAH', 'HUNGARY', 'SCIENTIST'),
 (1975, 'PHYSICS', 'PETER', 'CHILE', 'SCIENTIST');

SELECT * FROM NOBEL_WIN;

--select all records from the NOBEL_WINtable where the subject does not start with 'P'
SELECT * FROM NOBEL_WIN
WHERE SUBJECT NOT LIKE 'P%';

SELECT WINNER || '(' || SUBSTR(SUBJECT, 1, 1) || ')' AS WINNER FROM NOBEL_WIN; --(column_name,start, steps)

--HANNES ALFEVEN(P)
--LOUIS NEEL(P)
--MARTIN(B)