CREATE TABLE IF NOT EXISTS CUSTOMER (
  CUSTOMER_ID PRIMARY KEY,
  NAME TEXT NOT NULL,
  ADDRESS TEXT,
  PHONE TEXT,
  GRADE INTEGER
);

INSERT INTO CUSTOMER(CUSTOMER_ID,NAME,ADDRESS,PHONE,GRADE) VALUES
   ('001','JAKE','NEW YORK','****','85')
   ('002','MARIA','CHICAGO','****','90')
   ('001','JACOB','NEW YORK','****','100')
   ('001','LISA','MICHIGAN','****','100')
   ('001','HAYES','NEW YORK','****','100')

SELECT * FROM CUSTOMER;

SELECT * FROM CUSTOMER WHERE GRADE = 100 AND ADDRESS = 'NEW YORK';

SELECT * FROM CUSTOMER WHERE GRADE = 100 OR ADDRESS = 'NEW YORK';